### ISSUE TITLE
Dashboard UI Modifications

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#100]
The following changes to the UI dashboard need to be created.
- Remove scrolling bars beside Call and Raw Materials Location cards
- Add separating lines between elements on the Raw Material card
- Remove image placeholder in Raw Material card
- Remove Price Trends card

**Comment by tremainebuchanan** [comment]
@nick, can you tell me if you completed this as yet. I stumbled upon the solution whilst implementing the price dashboard ui.

**Comment by nickwxo** [comment]
@tremainebuchanan No I haven't completed this yet but it would have been one of the first things I tackled today. Feel free to share the solution though. It'll save me some time. :+1:
