### ISSUE TITLE
Demand Page - Buyer Reports should open in new tab/window

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#136]
Currently when the user clicks on the link on a Demand Profile page to view a buyer report, it open the buyer report in the same window, taking the user away from the application. This is not ideal for a non-technical user as there is no navigation on the report page to get back to the application.

A preferable UI would be fore the buyer report to open in a new  tab in the browser, preserving the application tab

**Comment by tremainebuchanan** [comment]
@paradoxxjm based on pull request https://github.com/slashroots/jas-mis-app/pull/129, this matter was resolved. Closing issue accordingly.
