### ISSUE TITLE
Random Application Error on Heroku Staging

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#21]
The current staging instance randomly fails with an "application" error. The cause of this error was initially thought to be timeouts during the uploading of significant datasets during the setup of the instance, however it has occurred at least once through the course of the weekend.

See the below image for error message.

![jasmic_applicationerror](https://cloud.githubusercontent.com/assets/406181/7787664/faf31c62-01dc-11e5-8f9b-ce2fac0304ca.png)

**Comment by paradoxxjm** [comment]
After restarting the dyno this morning, the application is back down again (~1 hr later).

**Comment by matjames007** [comment]
@paradoxxjm: Keep monitoring the site.  I figure out how to properly restart the dynos, I haven't seen any errors since.  I am also monitoring the logs live.  The logs haven't said why the error, but I suspect it is as a result of not properly restarting.

**Comment by matjames007** [comment]
I think I can mark this closed.  The proper restart seemed to fix this.
