### ISSUE TITLE
Farmer Profile - Membership Card Not Yet Implemented

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#24]
The Membership Card, which is supposed to show information about a farmer's JAS membership history and records has not yet been implemented / added to the design of the farmer profile.

**Comment by paradoxxjm** [comment]
@nick22891, you had implemented this already correct? I'm seeing something already on Master with the correct layouts. However, it seems that the Membership "Status" field is still hardcoded. 

Let me know if this is actually correct.

**Comment by nickwxo** [comment]
This is already done and the hard coded  status thing was fixed weeks ago.

**Comment by nickwxo** [comment]
@paradoxxjm Not sure if the branch that was fixed on has been merged into master yet but it should have been. Will check.

**Comment by paradoxxjm** [comment]
@nick22891 can you confirm the status of this and close if needed.

**Comment by nickwxo** [comment]
Done.
