### ISSUE TITLE
Adding a district and extension picker

### ISSUE THREAD

**Issue by matjames007** [slashroots/jas-mis-app#26]
Currently I have district and extension for a farm being an ID field.  This should be changed to a control box/picker similar to that of the crop/variety selection.  This requires a database schema change.

**Comment by paradoxxjm** [comment]
This is related to issue #23. Should we merge /  close one?

**Comment by matjames007** [comment]
Sorry I hadn't realized... I flagged #23 as duplicate.

**Comment by matjames007** [comment]
Resolved this in commit: d9bda6c5946e73e05971019b6c8801d01dc0c0bc
