### ISSUE TITLE
Change Farm "Add" Button Label text to "Save"

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#3]
I would recommend changing the text for button adding a new farm record from "Add" to "Save". The rationale being that the "Plus" button for initiating the creation of a new farm already implies the intention to "Add". Once the data is entered, what the person will be doing is saving the record. So using the label is more intuitive.

**Comment by matjames007** [comment]
Ok I accepted the changes and I have propagated to commit: 502d36430bad95d50758089c38894a7e697d2539
