### ISSUE TITLE
Farmer Profile - Text Entry Fields for new demands allow negative data inputs

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#35]
A user can enter a negative figure for data fields (quantity and unit price) when creating a new supply for a farmer.

See example: https://jas-mis-app-staging.herokuapp.com/home/#/farmer/55762940ecd6cd88469ad0b6

**Comment by matjames007** [comment]
Fixed in commit: 2436efe7b1cc1d320f5a11c1f5761118f5235d7f
