### ISSUE TITLE
New Supply Input Form (Farmer Profile) - Available Date and End Date labels do not match input format 

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#36]
The labels for the "Available Date (yyyy-MM-dd)" and "End Date (yyyy-MM-dd)" do not match the format for the input text fields (MM-dd-yyyy).

**Comment by matjames007** [comment]
depending on the browser the format differs...this happens when you build against Safari

**Comment by paradoxxjm** [comment]
Its that finicky!? This is the build in Angular datepicker? Or is it a library from the Interweb?

**Comment by matjames007** [comment]
nah it was my mistake... angular doesn't have a built in picker.  Each browser has it's own controls for dates except safari >.<
