### ISSUE TITLE
Demands Result Page - "View More" on Demand Detail Card not linked to Demand detail page

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#38]
The "View More" button and arrows on the context card for a selected row do not link to the Demand Results page of that particular view. As a result, there is now way to get to the Demand Detail Page from the Demand Results Page.

**Comment by matjames007** [comment]
Fixed in commit: 5adfee56e3a959499a37fe8240dc72b8e93cb42e
