### ISSUE TITLE
Add Farm Entry Form "Cancel" Button

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#4]
I would recommend we add a "Cancel" button to the new Farm form. So if a user presses the button by accident or no longer wants to enter a farm, they can remove the data entry fields from the screen without having to reload or change the page.

This behaviour could be added to other form entries as well.

**Comment by matjames007** [comment]
I have accepted the request for enhancement and the details are in the commit: 502d36430bad95d50758089c38894a7e697d2539
