### ISSUE TITLE
Farmer Profile - Add Cancel Button to Farmer Details Edit Form

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#40]
Similar to issue #4 there is no "cancel" button on the edit page for the farmer details form. The only way for the user to exit the edit form is by pressing the "back" button in the browser or clicking elsewhere.

Example: https://jas-mis-app-staging.herokuapp.com/home#/farmer/5576294becd6cd88469b25dc/edit

**Comment by tremainebuchanan** [comment]
Issue now closed. Cancel button implemented. Just need to find out if any color will be added to either the cancel button or the add button to add contrast.
