### ISSUE TITLE
User Roles and Access Levels

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#42]
The implementation of different user roles (e.g call centre rep, administrator, etc,.) and their respect user access levels to manage privileges.
- [ ]  Create list of user types
- [ ]  Create list of different user privileges
- [ ]  Implement user types and priveledges
- [ ]  Modify UI to align with user privileges/roles

**Comment by matjames007** [comment]
In Commit: b65153b0db53d1d22c6e1ab1e6e377ecef6303b2 it has the features for two roles (administrator and "everyone else").  This is however extensible!  The priviledges are done at a API end point basis.  example:  Only administrators can create a parish.  Everyone else can read parishes.
