### ISSUE TITLE
Demand Page - No link back to Buyer Profile Page

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#43]
Currently there is no link back to the buyer profile page from a specific demand page. To get back to a buyer profile page, the user has to search for the buyer using the global search and then find them in the list of buyers. 

It would be better if the buyer name acted as a link back to the buyer profile page.

**Comment by matjames007** [comment]
Resolved commit: 5f45dd5df0cb4f3dab665ec607d1797f8dacaf24
