### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#44]
A login screen for the application will need to be created to manage authentication of the different types of users. This will utilize the user roles and user access implemented in #42.

**Comment by matjames007** [comment]
A scaffolding has been created in commit: b65153b0db53d1d22c6e1ab1e6e377ecef6303b2.  Design hasn't been done or applied.

**Comment by matjames007** [comment]
Check it out in commit: 0c64996c695a51dc975d0ac3584efcf9484600a9
