### ISSUE TITLE
No Feedback for HTTP status code 401

### ISSUE THREAD

**Issue by matjames007** [slashroots/jas-mis-app#56]
We need to redirect the user to the login page if a 401 unauthorized error is thrown by the web service.

**Comment by tremainebuchanan** [comment]
Implemented a new function called redirect in the common.js file. It accepts a location or route name along with req and res params. The function is called in the else block after the common.isAuthenticated function call is made.

**Comment by matjames007** [comment]
Need to redirect using the client / angular application.  401 is a good response by the web service to an unauthorized client.

**Comment by matjames007** [comment]
Check out commit: 97ef1c792fd67413c24fd4745dac74863d2f272a
