### ISSUE TITLE
Farmer Profile Page - Make "Country" field under new Farm form uneditable

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#6]
The "Country" field in the form for the creation of a new farm should be uneditable. Currently it defaults to Jamaica as the location. Given that all farms will be within Jamaica for the foreseeable future, we should not give the user the opportunity to change it (accidentally or purposefully).

**Comment by matjames007** [comment]
The country fields have been removed from all forms.  I forgot to remove it from farms.  This has now been done and the database assumes 'Jamaica' if no country given.
