### ISSUE TITLE
Replace Current Floating Button with Angular Implementation

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#63]
Angular Material recently released an official implementation of the [Floating Button](https://material.angularjs.org/latest/#/demo/material.components.fabSpeedDial) that we have in the JAS application.

We should replace our implementation with the official one.

**Comment by matjames007** [comment]
The angular floating button that @nick22891 has in the `css-fixes` branch does not behave how we expect it to.  The alignment is also off.

<img width="164" alt="screen shot 2015-07-27 at 11 13 13 am" src="https://cloud.githubusercontent.com/assets/1425164/8911233/ba54439c-3450-11e5-8263-6fd0bac03d4a.png">

**Comment by nickwxo** [comment]
How specifically does it not behave correctly? Will tweak the alignment now. A bit of padding on the left should do the trick.

**Comment by matjames007** [comment]
The same behaviour of the buttons below appear after the floating button is clicked would be expected.  All buttons are visible.  Be careful how you do padding... remember the alignment will be different depending on the screen resolution.  A padding of 20px might get it centred on your resolution but might throw it off on another.  Please centre align it instead.  Refer to angular material docs.
