### ISSUE TITLE
Farmer Detail Page Implementation 

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#64]
Complete the outstanding design implementations of the Farmer Profile page. There are a number of cards and UI elements that have not yet been completed, such as the membership card, the related supplies and the transaction side bars that need to be completed.

See the below for the most recent mockup of the design.

https://drive.google.com/file/d/0Bx2lodNPolgPNVdUb1F0UVJsN0k/view?usp=sharing

**Comment by matjames007** [comment]
Just to be clear @paradoxxjm the side bars are completed in commit: 8c0fd3a83703f1b8c235d6c8c5b7d959c1548acc
The UI icons/images etc have not been completed for the rest of the mentioned cards.

**Comment by matjames007** [comment]
A commit has been made for the membership card but it still hasn't been completed.  Try not to leave the changes incomplete @nick22891 

<img width="739" alt="screen shot 2015-07-27 at 11 13 07 am" src="https://cloud.githubusercontent.com/assets/1425164/8911299/2b1f07b0-3451-11e5-9601-4d032d02758a.png">

**Comment by nickwxo** [comment]
I'm working on the alignment and the remaining icons for this now. Tremaine explained yesterday about making commits with unfinished implementations but I may have misunderstood Matthew last week when he said something about pushing an update anyway. That was when I was explaining my issue with the icons.
