### ISSUE TITLE
Active Demands & Active Supply List Page Table Columns missing titles 

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#66]
The table columns on the [demand listing](https://jas-mis-app-staging.herokuapp.com/home#/demands) and [supply listing](https://jas-mis-app-staging.herokuapp.com/home#/supplies) pages do not have titles. A user unfamiliar with the tables may have trouble understanding the information in each table column.

**Comment by matjames007** [comment]
Currently the tables are implemented with divs and not the table tag. Modify to a table tag and include the headings.
