### ISSUE TITLE
Login Redirect

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#71]
When a non-logged-in user or a user whose session has expires tries to access a part of the application it redirects them to the login screen for authentication. However, once the user is logged in, the application forwards them to the homepage. Instead, the application should redirect them to the original link/action that the user was requesting initially.

**Comment by matjames007** [comment]
See commit: b14d530d79d78f5a6f7714d5f5dcbfe7e21d147c
