### ISSUE TITLE
Administrator Dashboard

### ISSUE THREAD

**Issue by tremainebuchanan** [slashroots/jas-mis-app#78]
The creation of an admin dashboard to: 
1. Create users, crop types and units
2. Once a user is created, an email should be sent with a <application_url>/mongo_id to the new user. 
3. Once the user clicks the emailed link, the user is directed to a page within the application to update password.
4. Upon successful update, the user is directed to the dashboard of the application.

**Comment by paradoxxjm** [comment]
@tremainebuchanan so I actually think that this user story (issue) is waay too big. We probably definitely break it up into smaller features (speadsheet reference) and related user stories.
