### ISSUE TITLE
Transaction Workflow

### ISSUE THREAD

**Issue by matjames007** [slashroots/jas-mis-app#89]
**Background**

There are four possible states:
- Pending - This is the starting state of the process.  Can be thought of as pending review from buyer.
- Waiting - This state can mean that there is some established promise between the buyer and farmer and the transaction is awaiting inspection/validation/grading before a decision is made.
- Completed - This is a successful transaction between the buyer and farmer.
- Failed - This could be as a result of failing inspection/validation/grading/pricing/unavailability or any other reason why the produce has not met the requirements of the buyer.

![fsm](https://cloud.githubusercontent.com/assets/1425164/9125013/c52af1e4-3c61-11e5-9f53-484b44ec36cc.jpg)

**Current App**

Currently we can create a transaction in a pending state.  This is done whenever we produce a buyer report.  Each farmer in that report has a transaction created with the buyer that the report is directed to.  

**Next Steps**

I believe that the movement from `pending` to `completed` or `failed` can be achieved by using a simple table that displays all the transactions on the system.  This table would allow for modifications to the state and the input of a comment that is linked to the transaction.  In terms of table editing it could look like [this](http://demos.telerik.com/kendo-ui/grid/editing-popup).

**Comment by paradoxxjm** [comment]
This needs to be broken up in the smaller user stories (issues). @matjames007 and I had an initial conversation and it will be added. The proposed implementation may not be as difficult as we initially thought.
