### ISSUE TITLE
Buyer Report - Unable to Specify Multiple Email Recipients

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/jas-mis-app#94]
Recall that for a particular buyer, there are multiple employees that can request a purchase on that company's behalf. However, currently the buyer report defaults to sending to the company's main email address and there no way in the demand profile to modify the recipients of the email.

We should modify the side card to allow the selection of additional emails for a buyer.

**Comment by tremainebuchanan** [comment]
Issue duplicated. We will now close this issue and solve same under issue #107
